version: '3.7'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn mysite.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static:/usr/src/mysite/static
      - ./:/usr/src/mysite
      - ./db.sqlite3:/usr/src/mysite/db.sqlite3
    ports:
      - 8000:8000
    env_file:
      - ./.env.prod

  nginx:
    build: ./nginx
    volumes:
      - static:/usr/src/mysite/static
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  static:
