# Generated by Django 2.1.7 on 2019-03-04 14:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thema',
            name='datum',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 4, 14, 37, 56, 528647), verbose_name='Erstelldatum'),
        ),
    ]
