# Generated by Django 2.1.7 on 2019-03-04 14:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190304_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thema',
            name='datum',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 4, 14, 40, 9, 366504, tzinfo=utc), verbose_name='Erstelldatum'),
        ),
    ]
