# Generated by Django 2.1.7 on 2019-03-04 14:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190304_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thema',
            name='datum',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Erstelldatum'),
        ),
    ]
