# Generated by Django 2.1.7 on 2019-03-05 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190304_1441'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('beschreibung', models.CharField(max_length=200)),
                ('link', models.CharField(default=1, max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Fächer',
            },
        ),
        migrations.CreateModel(
            name='Karten',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frage', models.CharField(max_length=200)),
                ('antwort', models.CharField(max_length=200)),
                ('link', models.CharField(default=1, max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Karten',
            },
        ),
        migrations.AddField(
            model_name='thema',
            name='link',
            field=models.CharField(default=1, max_length=200),
        ),
        migrations.AddField(
            model_name='karten',
            name='karten_thema',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.Thema', verbose_name='Thema'),
        ),
        migrations.AddField(
            model_name='thema',
            name='thema_fach',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.Fach', verbose_name='dasfach'),
        ),
    ]
