# Generated by Django 2.1.7 on 2019-03-09 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_thema_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='thema',
            name='is_published',
            field=models.CharField(default='nein', max_length=20),
        ),
    ]
