# Generated by Django 2.1.7 on 2019-03-09 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_thema_is_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='karten',
            name='link',
        ),
    ]
