# Generated by Django 2.1.7 on 2019-03-10 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_karten_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='karten',
            name='is_published',
            field=models.CharField(default='ja', max_length=20),
        ),
    ]
