# Generated by Django 2.1.7 on 2019-05-03 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_karten_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='thema',
            name='style',
            field=models.CharField(default='', max_length=200),
        ),
    ]
