# Generated by Django 2.1.7 on 2019-05-03 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_thema_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thema',
            name='style',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
