# Generated by Django 2.2.5 on 2019-11-26 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_thema_is_klausur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thema',
            name='is_klausur',
            field=models.BooleanField(default=False, verbose_name='Klausurthema?'),
        ),
    ]
