# Generated by Django 2.2.13 on 2020-10-27 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20191126_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thema',
            name='style',
            field=models.CharField(blank=True, default='', max_length=5000),
        ),
    ]
