# Generated by Django 2.2.13 on 2020-10-27 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20201027_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thema',
            name='style',
            field=models.CharField(blank=True, default='', max_length=25000),
        ),
    ]
